# -*- coding: utf-8 -*-
"""biasclean_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VkcJ0Ak4cZ6u8mZMYqeabisIR6wPinxV
"""

"""
Flask Web Wrapper for Universal BiasClean Pipeline - biasclean_app.py
Production Deployment for Render.com
Author: CS Principal Engineer with 20 years Python experience
"""

import os
import json
import tempfile
import traceback
from datetime import datetime
from typing import Dict, Any

import pandas as pd
from flask import Flask, request, jsonify, render_template_string

# Import your pipeline (adjusted for deployment)
# Note: We're removing Colab/UI dependencies while keeping core logic
from biasclean_7 import UniversalBiasClean, DOMAIN_CONFIGS

# ============================================================================
# FLASK APP CONFIGURATION
# ============================================================================

app = Flask(__name__)
app.config['MAX_CONTENT_LENGTH'] = 50 * 1024 * 1024  # 50MB max file size
app.config['UPLOAD_FOLDER'] = tempfile.gettempdir()

# ============================================================================
# HTML TEMPLATE FOR WEB INTERFACE
# ============================================================================

HTML_TEMPLATE = '''
<!DOCTYPE html>
<html>
<head>
    <title>Universal BiasClean v2.1 - 7 Domain Edition</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f5f5f5;
            line-height: 1.6;
        }
        .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            border-radius: 10px;
            margin-bottom: 30px;
            text-align: center;
        }
        .container {
            display: flex;
            flex-wrap: wrap;
            gap: 30px;
        }
        .upload-section, .results-section {
            background: white;
            padding: 25px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            flex: 1;
            min-width: 300px;
        }
        .form-group {
            margin-bottom: 20px;
        }
        label {
            display: block;
            margin-bottom: 8px;
            font-weight: 600;
            color: #333;
        }
        select, input[type="file"], input[type="number"] {
            width: 100%;
            padding: 10px;
            border: 1px solid #ddd;
            border-radius: 4px;
            font-size: 14px;
        }
        .btn {
            background: #667eea;
            color: white;
            border: none;
            padding: 12px 24px;
            border-radius: 4px;
            cursor: pointer;
            font-size: 16px;
            font-weight: 600;
            transition: background 0.3s;
            width: 100%;
        }
        .btn:hover {
            background: #5a67d8;
        }
        .btn:disabled {
            background: #a0aec0;
            cursor: not-allowed;
        }
        .result-item {
            background: #f8f9fa;
            padding: 15px;
            margin-bottom: 15px;
            border-radius: 4px;
            border-left: 4px solid #667eea;
        }
        .metric {
            display: inline-block;
            background: #f8f9fa;
            padding: 10px 15px;
            margin: 5px;
            border-radius: 4px;
            border-left: 4px solid #667eea;
        }
        .metric-value {
            font-size: 20px;
            font-weight: bold;
            color: #667eea;
        }
        .metric-label {
            font-size: 12px;
            color: #666;
        }
        .success { color: #27ae60; }
        .warning { color: #f39c12; }
        .error { color: #e74c3c; }
        .loading {
            display: none;
            text-align: center;
            padding: 20px;
        }
        .spinner {
            border: 4px solid #f3f3f3;
            border-top: 4px solid #667eea;
            border-radius: 50%;
            width: 40px;
            height: 40px;
            animation: spin 1s linear infinite;
            margin: 0 auto 15px;
        }
        @keyframes spin {
            0% { transform: rotate(0deg); }
            100% { transform: rotate(360deg); }
        }
        .domain-info {
            background: #e3f2fd;
            padding: 15px;
            border-radius: 4px;
            margin-bottom: 20px;
        }
        .download-link {
            display: inline-block;
            background: #27ae60;
            color: white;
            padding: 10px 20px;
            border-radius: 4px;
            text-decoration: none;
            margin-top: 10px;
        }
        .download-link:hover {
            background: #219653;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Universal BiasClean v2.1</h1>
        <p>7-Domain Edition with Weight-Prioritized Bias Mitigation</p>
        <p style="font-size: 14px; opacity: 0.9;">Hierarchical Taxonomy + Constraint Validation Framework</p>
    </div>

    <div class="container">
        <div class="upload-section">
            <h2>Upload Dataset</h2>

            <div class="domain-info">
                <h3>Available Domains (UK 2025 Methodology)</h3>
                <p><strong>Justice</strong>, <strong>Health</strong>, <strong>Finance</strong>, <strong>Hiring</strong>,
                <strong>Education</strong>, <strong>Business</strong>, <strong>Governance</strong></p>
                <p><em>Each domain has specific weight priorities for bias mitigation</em></p>
            </div>

            <form id="uploadForm" enctype="multipart/form-data">
                <div class="form-group">
                    <label for="csvFile">CSV File</label>
                    <input type="file" id="csvFile" name="file" accept=".csv" required>
                    <p style="font-size: 12px; color: #666; margin-top: 5px;">Max file size: 50MB</p>
                </div>

                <div class="form-group">
                    <label for="domain">Domain</label>
                    <select id="domain" name="domain" required>
                        <option value="justice">Justice (Default)</option>
                        <option value="health">Healthcare</option>
                        <option value="finance">Finance</option>
                        <option value="hiring">Hiring</option>
                        <option value="education">Education</option>
                        <option value="business">Business</option>
                        <option value="governance">Governance</option>
                    </select>
                </div>

                <div class="form-group">
                    <label for="targetColumn">Target Column (Optional)</label>
                    <input type="text" id="targetColumn" name="target_column"
                           placeholder="Auto-detected if left blank">
                    <p style="font-size: 12px; color: #666; margin-top: 5px;">
                        Name of the binary outcome column (e.g., 'loan_approved', 'hired')
                    </p>
                </div>

                <div class="form-group">
                    <label for="threshold">Auto-Approval Threshold (0.0-1.0)</label>
                    <input type="number" id="threshold" name="threshold"
                           min="0.0" max="1.0" step="0.05" value="0.80">
                    <p style="font-size: 12px; color: #666; margin-top: 5px;">
                        Higher values = stricter mapping validation
                    </p>
                </div>

                <button type="submit" class="btn" id="submitBtn">Analyze Bias</button>
            </form>

            <div class="loading" id="loading">
                <div class="spinner"></div>
                <p>Processing dataset...</p>
                <p>This may take a few minutes for large datasets</p>
            </div>
        </div>

        <div class="results-section">
            <h2>Results</h2>
            <div id="resultsContainer">
                <p style="color: #666; font-style: italic;">
                    Upload a CSV file to analyze bias and generate corrected dataset
                </p>
            </div>
        </div>
    </div>

    <script>
        document.getElementById('uploadForm').addEventListener('submit', async function(e) {
            e.preventDefault();

            const submitBtn = document.getElementById('submitBtn');
            const loading = document.getElementById('loading');
            const resultsContainer = document.getElementById('resultsContainer');

            // Show loading, disable button
            submitBtn.disabled = true;
            loading.style.display = 'block';
            resultsContainer.innerHTML = '<p>Processing...</p>';

            const formData = new FormData(this);

            try {
                const response = await fetch('/analyze', {
                    method: 'POST',
                    body: formData
                });

                const data = await response.json();

                if (response.ok) {
                    // Display results
                    let html = `
                        <div class="result-item">
                            <h3>Analysis Complete</h3>
                            <p><strong>Domain:</strong> ${data.domain}</p>
                            <p><strong>Records Processed:</strong> ${data.records_processed}</p>
                            <p><strong>Columns Analyzed:</strong> ${data.columns_analyzed}</p>
                        </div>

                        <div class="result-item">
                            <h3>Bias Reduction</h3>
                            <div class="metric">
                                <div class="metric-value">${data.initial_bias.toFixed(4)} → ${data.final_bias.toFixed(4)}</div>
                                <div class="metric-label">Bias Score</div>
                            </div>
                            <div class="metric">
                                <div class="metric-value ${data.improvement > 0 ? 'success' : 'error'}">${data.improvement > 0 ? '+' : ''}${data.improvement.toFixed(1)}%</div>
                                <div class="metric-label">Improvement</div>
                            </div>
                        </div>
                    `;

                    if (data.significant_biases > 0) {
                        html += `
                            <div class="result-item">
                                <h3>Significant Biases Mitigated</h3>
                                <p><strong>Count:</strong> ${data.significant_biases}</p>
                                <p><strong>Features:</strong> ${data.biased_features.join(', ')}</p>
                            </div>
                        `;
                    }

                    if (data.download_url) {
                        html += `
                            <div class="result-item">
                                <h3>Download Results</h3>
                                <p>Corrected dataset with bias mitigation applied:</p>
                                <a href="${data.download_url}" class="download-link" download>
                                    Download Corrected CSV
                                </a>
                                <p style="font-size: 12px; color: #666; margin-top: 10px;">
                                    <em>This file will be deleted after 1 hour</em>
                                </p>
                            </div>
                        `;
                    }

                    resultsContainer.innerHTML = html;
                } else {
                    resultsContainer.innerHTML = `
                        <div class="result-item error">
                            <h3>Error</h3>
                            <p><strong>${data.error}</strong></p>
                            <p>${data.details || ''}</p>
                        </div>
                    `;
                }
            } catch (error) {
                resultsContainer.innerHTML = `
                    <div class="result-item error">
                        <h3>Network Error</h3>
                        <p>Please check your connection and try again.</p>
                    </div>
                `;
            } finally {
                // Hide loading, enable button
                submitBtn.disabled = false;
                loading.style.display = 'none';
            }
        });
    </script>
</body>
</html>
'''

# ============================================================================
# ROUTES
# ============================================================================

@app.route('/')
def index():
    """Serve the main interface"""
    return render_template_string(HTML_TEMPLATE)


@app.route('/analyze', methods=['POST'])
def analyze():
    """Process CSV file and run bias analysis"""
    try:
        # Validate file upload
        if 'file' not in request.files:
            return jsonify({
                'error': 'No file uploaded',
                'details': 'Please select a CSV file'
            }), 400

        file = request.files['file']
        if file.filename == '':
            return jsonify({
                'error': 'No file selected',
                'details': 'Please select a CSV file'
            }), 400

        if not file.filename.lower().endswith('.csv'):
            return jsonify({
                'error': 'Invalid file type',
                'details': 'Please upload a CSV file'
            }), 400

        # Get parameters
        domain = request.form.get('domain', 'justice')
        target_column = request.form.get('target_column', None)
        if target_column == '':
            target_column = None

        threshold = request.form.get('threshold', '0.80')
        try:
            threshold = float(threshold)
            threshold = max(0.0, min(1.0, threshold))
        except ValueError:
            threshold = 0.80

        # Save uploaded file
        temp_file = tempfile.NamedTemporaryFile(
            suffix='.csv',
            delete=False,
            dir=app.config['UPLOAD_FOLDER']
        )
        file.save(temp_file.name)
        temp_file.close()

        # Read CSV
        try:
            df = pd.read_csv(temp_file.name)
        except Exception as e:
            os.unlink(temp_file.name)
            return jsonify({
                'error': 'Failed to read CSV file',
                'details': str(e)
            }), 400

        # Initialize pipeline
        pipeline = UniversalBiasClean(domain=domain)

        # Process dataset
        results = pipeline.process_dataset(
            df=df,
            target_column=target_column,
            auto_approve_threshold=threshold
        )

        # Generate corrected dataset file
        corrected_df = results.get('corrected_df')
        if corrected_df is not None:
            output_filename = f"biasclean_corrected_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv"
            output_path = os.path.join(app.config['UPLOAD_FOLDER'], output_filename)
            corrected_df.to_csv(output_path, index=False)
            download_url = f"/download/{output_filename}"
        else:
            download_url = None

        # Extract key metrics for response
        diagnostics = results.get('diagnostics', {})
        validation = results.get('validation', {})

        initial_bias = diagnostics.get('initial_bias_score', 0)
        final_bias = diagnostics.get('final_bias_score', initial_bias)
        improvement = ((initial_bias - final_bias) / initial_bias * 100) if initial_bias > 0 else 0

        # Get biased features
        biased_features = []
        feature_tests = diagnostics.get('feature_tests', {})
        for feature, test in feature_tests.items():
            if test.get('significant_bias', False):
                biased_features.append(feature)

        # Clean up uploaded file
        os.unlink(temp_file.name)

        return jsonify({
            'success': True,
            'domain': domain,
            'records_processed': len(df),
            'columns_analyzed': len(df.columns),
            'initial_bias': initial_bias,
            'final_bias': final_bias,
            'improvement': improvement,
            'significant_biases': len(biased_features),
            'biased_features': biased_features,
            'data_retention': validation.get('data_integrity', {}).get('retention_rate', 100),
            'download_url': download_url,
            'timestamp': datetime.now().isoformat()
        })

    except Exception as e:
        # Clean up temp files if they exist
        if 'temp_file' in locals() and os.path.exists(temp_file.name):
            os.unlink(temp_file.name)

        return jsonify({
            'error': 'Pipeline execution failed',
            'details': str(e),
            'traceback': traceback.format_exc()
        }), 500


@app.route('/download/<filename>', methods=['GET'])
def download(filename):
    """Serve corrected dataset for download"""
    try:
        file_path = os.path.join(app.config['UPLOAD_FOLDER'], filename)

        if not os.path.exists(file_path):
            return jsonify({
                'error': 'File not found',
                'details': 'The requested file has expired or was deleted'
            }), 404

        # Check if file is a CSV (security)
        if not filename.lower().endswith('.csv'):
            return jsonify({
                'error': 'Invalid file type'
            }), 400

        # Return file for download
        from flask import send_file
        return send_file(
            file_path,
            as_attachment=True,
            download_name=f"biasclean_corrected_{datetime.now().strftime('%Y%m%d')}.csv",
            mimetype='text/csv'
        )

    except Exception as e:
        return jsonify({
            'error': 'Download failed',
            'details': str(e)
        }), 500


@app.route('/health', methods=['GET'])
def health():
    """Health check endpoint for Render"""
    return jsonify({
        'status': 'healthy',
        'timestamp': datetime.now().isoformat(),
        'service': 'Universal BiasClean v2.1',
        'domains_available': list(DOMAIN_CONFIGS.keys())
    })


# ============================================================================
# SCHEDULED CLEANUP (Optional - for production)
# ============================================================================

def cleanup_old_files(max_age_hours=1):
    """Remove old uploaded files"""
    try:
        now = datetime.now().timestamp()
        for filename in os.listdir(app.config['UPLOAD_FOLDER']):
            if filename.startswith('biasclean_'):
                filepath = os.path.join(app.config['UPLOAD_FOLDER'], filename)
                file_age = now - os.path.getmtime(filepath)
                if file_age > (max_age_hours * 3600):
                    os.unlink(filepath)
                    print(f"Cleaned up old file: {filename}")
    except Exception as e:
        print(f"Cleanup error: {e}")


# ============================================================================
# MAIN ENTRY POINT
# ============================================================================

if __name__ == '__main__':
    # Create upload directory if it doesn't exist
    os.makedirs(app.config['UPLOAD_FOLDER'], exist_ok=True)

    # Run cleanup on startup
    cleanup_old_files()

    # Start Flask server
    port = int(os.environ.get('PORT', 5000))
    app.run(host='0.0.0.0', port=port, debug=False)